# Generated by Django 5.0.6 on 2024-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerAuthTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(db_column="customer_auth_access_token", null=True),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        db_column="customer_auth_refresh_token", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fd_customer_auth_tokens",
            },
        ),
    ]
