# Generated by Django 5.0.6 on 2024-06-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fd_customer_Profile",
            },
        ),
        migrations.CreateModel(
            name="CustomerOTP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "customer_otp_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("otp", models.CharField(max_length=255)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customerProfile.customerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ec_customer_otp",
            },
        ),
    ]
